services:
  db_postgres:
    image: postgres:13
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students
    volumes:
      - postgres_students:/var/lib/postgresql/data

  node_app_students:
    container_name: node_app_students
    build: ./back-end
    ports:
      - 5000:5000
    links:
      - db_postgres
    depends_on:
      - db_postgres
    env_file:
      - back-end/.env
    volumes:
      - .:/usr/src

  react_app_students:
    container_name: react_app_students
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_postgres
      - node_app_students
      - react_app_students

volumes:
  postgres_students:
  build_react:
