name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db_postgres:5432/students-test?schema=public"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run node_app_students npm run test
      - name: Build
        run: npm i && npm run build
